# Generated by Django 3.1 on 2020-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('course_number', models.IntegerField(default='', max_length=10)),
                ('instructor_name', models.CharField(default='', max_length=60)),
                ('duration', models.FloatField(default='', max_length=60)),
            ],
        ),
    ]
